#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=4:00:00
#PBS -N wmaSeg
#PBS -V

rm -rf tracts

#TODO..
module load singularity 2> /dev/null
singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main


if [ ! -s output.mat ];
then
	echo "output missing"
	exit 1
fi
